### ISSUE TITLE
Just wondering if this will work...

### ISSUE THREAD

**Issue by ghost** [br3athein/.dotfiles#1]
This is a dummy issue submitted w/o leaving Emacs using Magithub package.
Purpose: try out what this package got up it's sleeve on a repo that I manage personally

**Comment by PanarinM** [comment]
@arkostyuk

**Comment by br3athein** [comment]
@PanarinM

**Comment by PanarinM** [comment]
@br3athein https://media.giphy.com/media/13OYNXi0uTM6vS/giphy.gif

**Comment by br3athein** [comment]
@br3athein
